### PR TITLE
Closes #135 -fixed some admin functionality and addded who you are logged in

### LINKED ISSUE #135: Navbar Update
As a user,
when I sign in,
I should see a message in the nave bar that I am logged in

### PR DESCRIPTION
**Pull request by slotaj**

### CODE REVIEW

File: app/controllers/venues/managers_controller.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@ def create
   end
 
   def destroy
-    venue = current_user.venues.find_by(url:params[:venue])
+    venue = find_venue
```
Comment (stevepentler) [inline app/controllers/venues/managers_controller.rb]: Don't we want to leave this as current_user to we can't open a security gap? Or are there checks prior?

File: app/views/shared/admin/_nav.html.erb [hunk 2]
```diff
@@ -4,6 +4,7 @@
     <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
     <ul class="right hide-on-med-and-down" style = "padding-right: 10px">
       <% if current_user %>
+        <li><%= "Logged in as #{current_user.username}" %></li>
```
Comment (stevepentler) [inline app/views/shared/admin/_nav.html.erb]: What a fantastic USER EXPERIENCE!
